### PR TITLE
Create bgm.js

### PR DESCRIPTION
**Pull request by mrroxle**
Signed-off-by: mrroxle <114426297+mrroxle@users.noreply.github.com>

### CODE REVIEW

**Comment by mrroxle** [comment]
ho

**Comment by mrroxle** [comment]
> ``

**Comment by mrroxle** [comment]
>

**Comment by mrroxle** [comment]
@A-d-i-t-h-y-a-n

**Comment by mrroxle** [comment]
@mask-sir

**Comment by A-d-i-t-h-y-a-n** [comment]
?

**Pull request closed without merging**
